// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyByhBp_tc9l6y5hOp3qaingd6mpApr6orw',
    appId: '1:76691596786:web:0ba914a5f0adbd7658776b',
    messagingSenderId: '76691596786',
    projectId: 'contact-trace-2025-bf4be',
    authDomain: 'contact-trace-2025-bf4be.firebaseapp.com',
    storageBucket: 'contact-trace-2025-bf4be.firebasestorage.app',
    measurementId: 'G-HQ0CZ6P18M',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDRHjm5OkR-xfQik0IVFx6eugf1KzhCA8Q',
    appId: '1:76691596786:android:f86945c2b135051658776b',
    messagingSenderId: '76691596786',
    projectId: 'contact-trace-2025-bf4be',
    storageBucket: 'contact-trace-2025-bf4be.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA7cAe7NDs02lk0513lFpDi6nuAqNnVTJA',
    appId: '1:76691596786:ios:beb25e7351db909658776b',
    messagingSenderId: '76691596786',
    projectId: 'contact-trace-2025-bf4be',
    storageBucket: 'contact-trace-2025-bf4be.firebasestorage.app',
    iosBundleId: 'com.example.capitisMad2Assignment8',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA7cAe7NDs02lk0513lFpDi6nuAqNnVTJA',
    appId: '1:76691596786:ios:beb25e7351db909658776b',
    messagingSenderId: '76691596786',
    projectId: 'contact-trace-2025-bf4be',
    storageBucket: 'contact-trace-2025-bf4be.firebasestorage.app',
    iosBundleId: 'com.example.capitisMad2Assignment8',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyByhBp_tc9l6y5hOp3qaingd6mpApr6orw',
    appId: '1:76691596786:web:091dc4bc8115f56958776b',
    messagingSenderId: '76691596786',
    projectId: 'contact-trace-2025-bf4be',
    authDomain: 'contact-trace-2025-bf4be.firebaseapp.com',
    storageBucket: 'contact-trace-2025-bf4be.firebasestorage.app',
    measurementId: 'G-739XS746Q2',
  );
}
