// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBuBtYe77hq6QOnTT6hszokyaqRXA2u4Ww',
    appId: '1:1049075016246:web:1c524fbae62b60bcb0ee97',
    messagingSenderId: '1049075016246',
    projectId: 'fir-act-46d4f',
    authDomain: 'fir-act-46d4f.firebaseapp.com',
    storageBucket: 'fir-act-46d4f.firebasestorage.app',
    measurementId: 'G-6WB15WLTVH',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBK7Zkg-J9rhokSN6LEsp8qbBglN9znGa0',
    appId: '1:1049075016246:android:472e9ad3fb77d977b0ee97',
    messagingSenderId: '1049075016246',
    projectId: 'fir-act-46d4f',
    storageBucket: 'fir-act-46d4f.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD8rf2NAoka73PpsxfydAiHgSZ6yjr5Srg',
    appId: '1:1049075016246:ios:91e25abc80b30a89b0ee97',
    messagingSenderId: '1049075016246',
    projectId: 'fir-act-46d4f',
    storageBucket: 'fir-act-46d4f.firebasestorage.app',
    iosBundleId: 'com.example.googleMapsFirebase',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD8rf2NAoka73PpsxfydAiHgSZ6yjr5Srg',
    appId: '1:1049075016246:ios:91e25abc80b30a89b0ee97',
    messagingSenderId: '1049075016246',
    projectId: 'fir-act-46d4f',
    storageBucket: 'fir-act-46d4f.firebasestorage.app',
    iosBundleId: 'com.example.googleMapsFirebase',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBuBtYe77hq6QOnTT6hszokyaqRXA2u4Ww',
    appId: '1:1049075016246:web:4ce35cbd86501f75b0ee97',
    messagingSenderId: '1049075016246',
    projectId: 'fir-act-46d4f',
    authDomain: 'fir-act-46d4f.firebaseapp.com',
    storageBucket: 'fir-act-46d4f.firebasestorage.app',
    measurementId: 'G-6ZZJ6YN3MK',
  );
}
